version: "3.5"
services:
  portal:
    image: 5minds/portal:3.5.0
    restart: always
    volumes:
      - ./atlas-ui/theme.css:/theme.css:ro
      - ./atlas-ui/config.json:/config.json:ro
      - ./atlas-ui/assets:/assets
    command: "--config /config.json --theme /theme.css --assets /assets"
    ports:
      - 8082:8082
    environment:
      useOAuth2: "true"
      oauth2Configuration__clientId: atlasui
      oauth2Configuration__scopes: test_resource
      applicationBaseUrl: http://localhost:8082
      atlasEngineUrl: http://localhost:10560
      customFormConfig__/.*/: http://localhost:3000

  atlas-authority:
    image: 5minds/5minds-authority
    volumes:
      - ./atlas-authority/storage/identity-server/:/app/storage/:rw
    ports:
      - 5000:5000

  engine:
    image: 5minds/engine:13.3.0
    ports:
      - 10560:10560
    volumes:
      - ./atlas-engine/config/:/etc/atlas-engine
      - ./atlas-engine/storage/:/root/.config/AtlasEngineFullstackServer/databases
    environment:
      - CONFIG_PATH=/etc/atlas-engine/sqlite.json
    command: --port 10560

  customforms:
    image: 5minds/processcube_sample_customforms
    build:
      context: ./CustomForms/desktop
      dockerfile: Dockerfile-develop
    volumes:
      - ./customforms/desktop/src/:/app/src/
    ports:
      - 3000:3000
    environment:
      - BROWSER=none

  bookservice:
    image: 5minds/booksservice
    build:
      context: ./src/BooksApi/
    ports:
      - 5011:80
