# build-state
FROM node:10

ARG NPM_TOKEN
RUN echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > /root/.npmrc

WORKDIR /app

COPY package-lock.json package.json ./
RUN npm ci

COPY public public
COPY tsconfig.json .

EXPOSE 3000
CMD ["npm", "start"]
